version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - networkName 
    volumes:
      - mongo-data:/data/db     #named volume  

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
      # mongo is same name as line 5 
    networks:
      - networkName 
  node-app:
    build:
      context: . 
    container_name: node-app
    ports:
      - "3001:3000"
    networks:
      - networkName 
volumes:
  mongo-data:
    driver: local          #specifies the docker that the data should be created on the local file system 

networks:
  networkName:


# docker-compose build /  docker-compose -f docker-compose.yaml up
# docker-compose up
# node server.js
# http://localhost:3001/    ui
# http://localhost:8081/ mongo db ui
