version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongoDBName
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - networkName 
    volumes:
      - ./data/db:/data/db  # Optional: Mount a volume for persistent data

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - networkName 

networks:
  networkName:


# docker-compose build /  docker-compose -f docker-compose.yaml up
# docker-compose up
# node server.js
# http://localhost:3000/    ui
# http://localhost:8081/ mongo db ui
